### ISSUE TITLE
Send "Authorization" header with requests to the backend

### ISSUE THREAD

**Issue by mathio** [Visual-Regression-Tracker/sdk-js#262]
# The issue

We have a VRT backend deployed. However it requires `Authorization` header for access in order not to be publicly accessible for anyone.

# Proposed solution

Add optional "authHeader" setting / `VRT_AUTH_HEADER` env variable. If present, its value can be [added to the AxiosRequestConfig](https://github.com/Visual-Regression-Tracker/sdk-js/blob/69c38721d8ec754e56f67cd27bb28b451c92aabb/lib/visualRegressionTracker.ts#L45-L50) as `Authorization` header to ensure it is sent with all requests to the backend. 

This allows the backend not to be publicly available. It provides support for any Authorization type since the full value of the header is provided from the config.

**Comment by pashidlos** [comment]
@mathio could you elaborate how this header is used by backend?
currently backend is protected by API key for SDK requests and Bearer token for the rest

**Comment by mathio** [comment]
There is a load balancer with basic auth in front of the VRT dashboard. 

There was a concern in our security team to open the VRT dashboard to the public. I think the main concern was the signups were open to anyone (which do not seem configurable).

**Comment by pashidlos** [comment]
@mathio yeah, atm anyone with access could create account with read-only access by default via Frontend 
have you tried to pass it via url like this?
```
  "apiUrl": "http://username:password@localhost:4200",
```

**Comment by mathio** [comment]
I will try the approach you suggested, thanks.

We want to run visual tests on a public project. Github Actions on public repos can not run using self-hosted containers. For private repos we use self-hosted containers with VPN setup.
