### ISSUE TITLE
Add configuration via config file or env variables

### ISSUE THREAD

**Issue by pashidlos** [Visual-Regression-Tracker/sdk-js#53]
Read file vrt.json from project root with structure:

```
{
      "apiUrl": "http://162.243.161.172:4200",
      "project": "VRT",
      "apiKey": "SECRET",
      "branchName": "master",
      "enableSoftAssert": false,
      "ciBuildId": "SOME_UNIQUE_ID"
}
```

env variables example:
```
VRT_APIURL="http://localhost:4200" 
VRT_PROJECT="Default project" 
VRT_APIKEY="tXZVHX0EA4YQM1MGDD" 
VRT_CIBUILDID="commit_sha" 
VRT_BRANCHNAME="develop" 
VRT_ENABLESOFTASSERT=true
```

Acceptance criteria:
- [x]  config variables are read from config file
- [x]  can start build with default constructor VisualRegressionTracker (without specific config)
- [x]  validation error is thrown in case required config properties are not set
- [x]  explicit config from code is overriding values from env variables
- [x]  env variables are overriding values from config file

**Comment by dcrowe** [comment]
Which properties are required? I think: apiUrl, project, apiKey, branchName

**Comment by dcrowe** [comment]
Added the python-sdk equivalent: https://github.com/Visual-Regression-Tracker/sdk-python/issues/18

**Comment by pashidlos** [comment]
> Which properties are required? I think: apiUrl, project, apiKey, branchName

yes

> Added the python-sdk equivalent: [Visual-Regression-Tracker/sdk-python#18](https://github.com/Visual-Regression-Tracker/sdk-python/issues/18)

wow, let me check it!
